services:
  user-service:
    container_name: user-service
    build:
      dockerfile: Dockerfile
    image: user-service:latest
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - user_network
  
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - D:\Practice\Toy-project\User-Service\postgres_data:/var/lib/postgresql/data
    networks:
      - user_network

networks:
  user_network:
    name: user-network
    driver: bridge